### ISSUE TITLE
Causes game to drop to 20fps on latest update that came out yesterday (26th)

### ISSUE THREAD

**Issue by ghost** [zelmer69/dualsense4GTA5#1]
Love this mod, would love to keep using it but for some reason it pins the framerate to 20fps when in use.

**Comment by zelmer69** [comment]
Hello. I know about problems with performance on newer versions. Currently I'm very busy to test some solution.
Yesterday I uploaded dll file that should fix problem on my discord server. 
If it's not hard for you join discord server than pick role @dualsense  and download that dll from server #download-s chanel in dualsense category.
I'm not promise it's fix but might help. In case it's not older version compatible with new dsx but doesn't have some systems. 
https://uk.gta5-mods.com/scripts/dualsense-adaptive-triggers-for-gtav
There is older version

**Comment by ghost** [comment]
Gave your discord version a try and the framerate was pretty weird, it kept going up and down over and over really fast like down to 20 up to 120 and a bunch of weird text showed up on my screen

**Comment by zelmer69** [comment]
> Gave your discord version a try and the framerate was pretty weird, it kept going up and down over and over really fast like down to 20 up to 120 and a bunch of weird text showed up on my screen

I would like to see text

**Comment by ghost** [comment]
It was just "0" at the bottom but it also made my screen flicker.
